Investment performance on QQQ
stargrep/2022-summer-bootcamp pull request #1
Opened 2022-08-15 06:57 UTC by jajdfkkk

test

2022-08-15 07:00 UTC, jajdfkkk commented
Please check the ''Investment on QQQ.py'' file

2022-08-27 03:46 UTC, stargrep requested changes

2022-08-27 03:46 UTC, stargrep commented on week03/project-1-Tony_Hu/investment on QQQ.py
> +warnings.filterwarnings('ignore')
why do we need the warning?

2022-08-27 03:46 UTC, stargrep commented on week03/project-1-Tony_Hu/investment on QQQ.py
> +# Evaluating performance
can you add some comments about the comparison of performances?

2022-08-27 03:46 UTC, stargrep commented on week03/project-1-Tony_Hu/scheduled_investment.py
> +
are you using this file or the 'investment on QQQ.py' for logic execution?

2022-08-27 03:46 UTC, stargrep commented on .idea/misc.xml
>  <?xml version="1.0" encoding="UTF-8"?>
to resolve merge conflict we can either remove these two .xml file or add them to .gitignore.

2022-08-27 09:59 UTC, jajdfkkk commented on week03/project-1-Tony_Hu/investment on QQQ.py
> +warnings.filterwarnings('ignore')
To filter warnings in the board below

2022-08-27 10:01 UTC, jajdfkkk commented on week03/project-1-Tony_Hu/investment on QQQ.py
> +# Evaluating performance
Comparison has been added to the PR. I integrate them as one plot.

2022-08-27 10:07 UTC, jajdfkkk commented on week03/project-1-Tony_Hu/scheduled_investment.py
> +
This file is not used. I'm using the ‘investment on QQQ.py' file. When I submit it said I've made changes in this file, but I didn't make any change.

2022-08-27 10:19 UTC, jajdfkkk commented on .idea/misc.xml
>  <?xml version="1.0" encoding="UTF-8"?>
I deleted 'misc.xml' and 'workspace.xml'

2022-08-30 07:52 UTC, closed without merging